name: build_deploy_netlify

on:
  push:
    branches: [ main, 'ci/**' ]

jobs:
  build_deploy_netlify:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn setup

      - name: 'Build'
        working-directory: modules/frontend
        run: yarn build:web

      - name: 'Deploy'
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=modules/frontend/web-build --prod

